accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [

    path("signup/", SignUpView.as_view(), name="signup"),
]

gonz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]

pages/urls.py
from django.urls import path
from .views import IndexView, TourView, AgentView, TourDetailView, AgentDetailView, TourCreateView, TourUpdateView, TourDeleteView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('tour/', TourView.as_view(), name='tour'),
    path('tour_detail/<int:pk>/', TourDetailView.as_view(), name='tour_detail'),
    path("tour/create/", TourCreateView.as_view(), name='tour_create'),
    path("tour/<int:pk>/update/", TourUpdateView.as_view(), name='tour_update'),
    path("tour/<int:pk>/delete/", TourDeleteView.as_view(), name='tour_delete'),
    path('agent/', AgentView.as_view(), name='agent'),
    path('agent_detail/<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class CustomUser(AbstractUser):
    roles = models.CharField(max_length=50, null=True, blank=True, )

pages/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

import datetime

from django.contrib.auth import get_user_model
from django.conf import settings
# User = settings.AUTH_USER_MODEL
User = get_user_model()


# def get_agent():
#     return User.objects.added_by(username)


class Tour(models.Model):
    tour_name = models.CharField(max_length=200)
    agent = models.ForeignKey(
        User, to_field="username", on_delete=models.CASCADE)
    city_name = models.CharField(max_length=100)
    date = models.DateField(default=datetime.date.today)
    duration = models.IntegerField()
    price = models.IntegerField()
    body = models.TextField()

    def __str__(self):
        return self.tour_name

    def __str__(self):
        return self.city_name

    def get_absolute_url(self):
        return reverse("tour_detail", kwargs={"pk": self.pk})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserChangeForm):
        model = CustomUser
        # fields = UserCreationForm.Meta.fields + ("roles",)

        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "roles",
        )


class CostomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        #fields = UserChangeForm.Meta.fields

        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "roles",
        )

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

pages/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, ListView, DetailView
from django.shortcuts import render
from .models import Tour
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings

User = get_user_model()


# Modify tours info

# Create your views here.


class IndexView(TemplateView):
    template_name = "pages/index.html"


# Tours
class TourView(ListView):
    model = Tour
    template_name = "pages/tour.html"


class TourDetailView(DetailView):
    model = Tour
    template_name = "pages/tour_detail.html"


class TourCreateView(CreateView):
    model = Tour
    template_name = "pages/tour_create.html"

    fields = ["tour_name", "agent", "city_name",
              "date", "duration", "price", "body"]


class TourUpdateView(UpdateView):
    model = Tour
    template_name = "pages/tour_update.html"

    fields = ["tour_name", "city_name", "date", "duration", "price", "body"]


class TourDeleteView(DeleteView):
    model = Tour
    template_name = "pages/tour_delete.html"
    success_url = reverse_lazy("tour")

# Agents


class AgentView(ListView):
    model = User
    template_name = "pages/agent.html"


class AgentDetailView(DetailView):
    model = User
    template_name = "pages/agent_detail.html"

pages/templates/pages/agent.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid pt-5 pb-5">
        <h1 class="display-4 py-2">Agent List</h1>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th>Agent Name</th>
                <th>Email</th> 
                <th>Position</th>        
            </tr>
            </thead>
            <tbody>    
            {% for user in object_list%}
            <tr>
                <td><a class="text-info text-decoration-none" href="{% url 'agent_detail' user.pk %}"> {{ user.username }}</a></td>                           
                <td> {{ user.email }} </td>
                <td> {{ user.roles }} </td>  
            </tr>
            {% empty %}
                <td>No Agent yet. </td>
            {% endfor %}
    
            </tbody>
        </table>
        {% if user.is_authentificated %}
            <a href="{% url 'tour_create' %}"> Create a new tour </a>
        {% endif %}
    </div>
{% endblock content %}

pages/templates/pages/agent_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container p-5">
    <h1 class="display-4 py-2">GoNZ Agent</h1>
    
    <table class="table .table-striped">
        <tr>
            <th>User Name: </th>
            <td>{{ customuser.username }}</td>
        </tr>
        <tr>
            <th>Agent Name: </th>
            <td>{{ customuser.first_name }} {{ customuser.last_name }}</td>
        </tr>
        <tr>
            <th>Email: </th>
            <td>{{ customuser.email }}</td>
        </tr>
        <tr>
            <th>Position: </th>
            <td>{{ customuser.roles }}</td>
        </tr>
    </table>
    <a class="btn btn-info mt-3" href="{% url 'agent' %}" role="button">Back to Agent List</a>
</div>
{% endblock content %}

pages/templates/pages/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {% endblock title%}

{% block content %}
<div class="container-fluid py-4">
    <h1 class="display-4 py-2">Travel around New Zealand with GoNZ</h1>
    <img src="{% static 'images/gonz_image.png' %}" class="img-fluid" alt="GoNZ nature images"/>
</div>
    
{% endblock content %}

pages/templates/pages/tour.html
{% extends "base.html" %}

{% block title %} Tour List {% endblock title%}

{% block content %}
<div class="container-fluid pt-5 pb-5">
    <h1 class="display-4 py-2">Tours List</h1>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>Tour Name</th>
                <th>City</th>
                <th>Duration</th>
                <th>Agent</th>
            </tr>
        </thead>
        <tbody>    
            {% for tour in tour_list %}
            <tr>
                <td><a class="text-info text-decoration-none" href="{% url 'tour_detail' tour.pk %}"> {{ tour.tour_name }} </a></td>
                <td>{{ tour.city_name }}</td>
                <td>{{ tour.duration }} Days</td>
                <td>{{ tour.agent }}</td>
            </tr>
            {% empty %}
                <td>No Tour yet.</td>
            {% endfor %}
        </tbody>
    </table>

    {% if user.is_authenticated %}
    <a class="btn btn-outline-info mt-3" href="{% url 'tour_create' %}" role="button">Create a new tour</a>
    {% endif %}
</div>

{% endblock content %}

pages/templates/pages/tour_create.html
{% extends "base.html" %}

{% block content %}
<div class="container p-5">
    <h1 class="display-4 py-3">Create New Tour</h1>
    <form action="" method="post">
        <div class="form-group">
        {% csrf_token %}{{ form.as_p }}
        <button type="submit" class="btn btn-info my-3">Save</button>
        </div>
    </form>
</div>
{% endblock content %}

pages/templates/pages/tour_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container p-5">
    <h1 class="display-4 py-3">Delete New Tour</h1>
    <form action="" method="post">
        <div class="form-group">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ tour.tour_name }}" ? </p>
        <button type="submit" class="btn btn-outline-info my-3">Confirm</button>
        </div>
    </form>
</div>
{% endblock content %}

pages/templates/pages/tour_detail.html
{% extends "base.html" %}

{% block title %} Tour Detail {% endblock title%}

{% block content %}
<div class="container py-5">
    <h3 class="py-3">{{ tour.tour_name }}</h3>
    <table class="table pt-5">
        <tbody>
          <tr>
            <th scope="row">Agent:</th>
            <td>{{ tour.agent }}</td>
          </tr>
          <tr>
            <th scope="row">City:</th>
            <td>{{ tour.city_name }}</td>
          </tr>
          <tr>
            <th scope="row">Date:</th>
            <td>{{ tour.date }}</td>
          </tr>
          <tr>
            <th scope="row">Duration:</th>
            <td>{{ tour.duration }} Days</td>
          </tr>
          <tr>
            <th scope="row">Price:</th>
            <td>${{ tour.price }} NZD</td>
          </tr>
          <tr>
            <th scope="row">Description:</th>
            <td>{{ tour.body }}</td>
          </tr>
        </tbody>
      </table>

      <span>
        <a class="btn btn-info mt-3 mr-2" href="{% url 'tour' %}" role="button">Back to Tour List</a>
        {% if user.is_authenticated %}
        
            <a class="btn btn-outline-info mt-3 mr-2" href="{% url 'tour_update' tour.pk %}" role="button">Update</a>
            <a class="btn btn-outline-info mt-3" href="{% url 'tour_delete' tour.pk %}" role="button">Delete</a> 
        {% endif %}
      </span>
    
</div>
{% endblock content %}

pages/templates/pages/tour_update.html
{% extends "base.html" %}

{% block content %}
<div class="container pt-5 pb-5">
    <h1 class="display-4 py-2">Update Tour</h1>
    <form action="" method="post">
        {% csrf_token %} {{ form.as_p }}
        <button class="btn btn-outline-info my-3" type="submit" value="Update">Update</button>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} GoNZ {% endblock title %}</title>

    <link rel="stylesheet" href="/static/CSS/main.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <div class="container-fluid">
        <header>
        <!-- header html 5 -->       
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'index' %}">GoNZ</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'tour' %}">Tours</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'agent' %}">Agents</a>
                            </li>
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link disabled text-white"> | Hi, {{ user.username}} |</a>  
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}"> Log Out </a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link disabled text-white"> | <a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'signup' %}"> Sign Up </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'login' %}"> Log In </a>
                                </li>       
                            {% endif %}
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>                
        </header>

        <div class="container">
            <main>
                
                {% block content %}
                
                {% endblock content %}
            </main>
            <footer>
                <p>© 2022 GoNZ Inc.</p>
            </footer>
        </div>
    </div><!-- End container-->
</body>
</html>